### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by Birdie0** [hdmifish/petal#2]
```
root@home-pc:~/petal# python3.5 run.py
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from petal import Petal
  File "/root/petal/petal/__init__.py", line 1, in <module>
    from .petal import Petal
  File "/root/petal/petal/petal.py", line 9, in <module>
    from .config import Config
  File "/root/petal/petal/config.py", line 1, in <module>
    from ruamel import yaml
ImportError: No module named 'ruamel'
```
same errors on Windows.

**Comment by hdmifish** [comment]
I forget something every time I write these.  Also I fixed the python install command. Thanks for the heads up. Changes have been made.
