### ISSUE TITLE
I found a bug~~~

### ISSUE THREAD

**Issue by Mazszy** [hdmifish/petal#6]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Mazzy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Mazzy\Desktop\Panda v3\petal\petal.py", line 264, in on_message
    if message.channel.id == self.config.get("roleGrant")["chan"] and discord.utils.get(self.mainsvr.roles, id=self.config.get("roleGrant")["role"]) not in message.author.roles:
  File "C:\Users\Mazzy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'petal.petal.Petal'>' object has no attribute 'mainsvr'
![2e642d1d36d84addb99e2761b7be54a5](https://cloud.githubusercontent.com/assets/25642209/22745547/d3438616-edd5-11e6-9ec1-fca68a3cc0cf.png)

**Comment by Mazszy** [comment]
AHH!! This bug torments me!

**Comment by hdmifish** [comment]
forgot to close
